---
  - name: "make sure to use project {{ THOTH_INFRA_NAMESPACE }}"
    command: "oc project {{ THOTH_INFRA_NAMESPACE }}"
    register: project_exists

  - name: importing Thoth's s2i-thoth-ubi8-py36 container image
    command: "oc import-image quay.io/thoth-station/s2i-thoth-ubi8-py36 --confirm"
    ignore_errors: false

  - name: importing legacy CentOS7 Python3.6 S2I container images from CentOS
    command: "oc import-image registry.centos.org/centos/python-36-centos7 --confirm"
    ignore_errors: true
    register: cent_os_registry

  - name: importing CentOS7 Python3.6 S2I container images from Docker
    command: "oc import-image docker.io/centos/python-36-centos7 --confirm"
    when: cent_os_registry is failed

  - name: importing required Fedora ImageStreamTags from upstream Registries
    command: "oc tag --namespace {{ THOTH_INFRA_NAMESPACE }} registry.fedoraproject.org/fedora:{{ item }} fedora:{{ item }}"
    with_items:
      - 27
      - 28
      - 29

  - name: create Thoth Core component's ImageStream
    shell: oc process --namespace "{{ THOTH_INFRA_NAMESPACE  }}" "{{ item }}" | oc apply -f -
    with_items:
      - "package-releases-imagestream"
      - "graph-refresh-imagestream"
      - "graph-sync-imagestream"
      - "package-extract-imagestream"
      - "package-releases-imagestream"
      - "cve-update-imagestream"
      - "adviser-imagestream"
      - "solver-imagestream"
      - "user-api-imagestream"
      - "cleanup-imagestream"
      - "isis-api-imagestream"
      - "management-api-imagestream"
      - "graph-sync-scheduler-imagestream"
      - "build-watcher-imagestream"
    ignore_errors: true

